export const siteData = {
  couple: {
    bride: "Naw Hae So Paw",
    groom: "Soe Yan Naing",
    combined: "Naw Hae So Paw & Soe Yan Naing",
    shortCombined: "Hae So Paw & Soe Yan",
  },
  parents: {
    bride: {
      father: "Saw Blut Htoo",
      mother: "Naw Blut Moo",
      label: "Daughter of",
    },
    groom: {
      father: "U Kyaw Soe",
      mother: "Daw Aye Aye Lwin",
      label: "Son of",
    },
  },
  verse: {
    text: "Unless the LORD builds the house, those who build it labor in vain.",
    reference: "Psalms 127:1",
  },
  event: {
    dayOfWeek: "Saturday",
    date: "9 May 2026",
    dateISO: "2026-05-09T09:00:00",
    timeStart: "9:00 AM",
    timeEnd: "12:00 PM",
    timeRange: "9:00 AM – 12:00 PM",
    venue: "Judson Church",
    venueSubtitle: "Yangon University",
    venueAddress: "R4JM+8M3, Yangon",
    googleMapSrc:
      "https://www.google.com/maps?q=R4JM%2B8M3%2C%20Yangon&output=embed",
    googleMapLink: "https://www.google.com/maps/search/?api=1&query=R4JM%2B8M3%2C%20Yangon",
  },
  slideshow: [
    "/images/slide-01.webp",
    "/images/slide-02.webp",
    "/images/slide-03.webp",
    "/images/slide-04.webp",
    "/images/slide-05.webp",
    "/images/slide-06.webp",
    "/images/slide-07.webp",
    "/images/slide-08.webp",
    "/images/slide-09.webp",
  ],
  gallery: [
    { src: "/images/gallery-01.webp", aspect: "portrait" },
    { src: "/images/gallery-02.webp", aspect: "landscape" },
    { src: "/images/gallery-03.webp", aspect: "portrait" },
    { src: "/images/gallery-04.webp", aspect: "square" },
    { src: "/images/gallery-05.webp", aspect: "landscape" },
    { src: "/images/gallery-06.webp", aspect: "portrait" },
    { src: "/images/gallery-07.webp", aspect: "square" },
    { src: "/images/gallery-08.webp", aspect: "portrait" },
    { src: "/images/gallery-09.webp", aspect: "landscape" },
    { src: "/images/gallery-10.webp", aspect: "portrait" },
    { src: "/images/gallery-11.webp", aspect: "landscape" },
    { src: "/images/gallery-12.webp", aspect: "portrait" },
    { src: "/images/gallery-13.webp", aspect: "square" },
    { src: "/images/gallery-14.webp", aspect: "portrait" },
    { src: "/images/hero-couple.webp", aspect: "landscape" },
  ],
} as const;
